import type { Instrument, SessionInfo } from "@/lib/types/market";

export const INSTRUMENTS: Instrument[] = [
  // Commodities — Gold first (primary trading instrument)
  {
    id: "XAU_USD",
    symbol: "XAU/USD",
    displayName: "Gold",
    category: "commodity",
    baseCurrency: "XAU",
    quoteCurrency: "USD",
    pipSize: 0.01,
    decimalPlaces: 2,
  },
  // Forex
  {
    id: "EUR_USD",
    symbol: "EUR/USD",
    displayName: "Euro / US Dollar",
    category: "forex",
    baseCurrency: "EUR",
    quoteCurrency: "USD",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  {
    id: "GBP_USD",
    symbol: "GBP/USD",
    displayName: "British Pound / US Dollar",
    category: "forex",
    baseCurrency: "GBP",
    quoteCurrency: "USD",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  {
    id: "AUD_USD",
    symbol: "AUD/USD",
    displayName: "Australian Dollar / US Dollar",
    category: "forex",
    baseCurrency: "AUD",
    quoteCurrency: "USD",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  {
    id: "NZD_USD",
    symbol: "NZD/USD",
    displayName: "New Zealand Dollar / US Dollar",
    category: "forex",
    baseCurrency: "NZD",
    quoteCurrency: "USD",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  {
    id: "USD_JPY",
    symbol: "USD/JPY",
    displayName: "US Dollar / Japanese Yen",
    category: "forex",
    baseCurrency: "USD",
    quoteCurrency: "JPY",
    pipSize: 0.01,
    decimalPlaces: 3,
  },
  {
    id: "USD_CAD",
    symbol: "USD/CAD",
    displayName: "US Dollar / Canadian Dollar",
    category: "forex",
    baseCurrency: "USD",
    quoteCurrency: "CAD",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  {
    id: "USD_CHF",
    symbol: "USD/CHF",
    displayName: "US Dollar / Swiss Franc",
    category: "forex",
    baseCurrency: "USD",
    quoteCurrency: "CHF",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  // Commodities — Silver, Oil (Gold moved to top)
  {
    id: "XAG_USD",
    symbol: "XAG/USD",
    displayName: "Silver",
    category: "commodity",
    baseCurrency: "XAG",
    quoteCurrency: "USD",
    pipSize: 0.001,
    decimalPlaces: 3,
  },
  {
    id: "USOIL",
    symbol: "USOIL",
    displayName: "US Oil (WTI)",
    category: "commodity",
    baseCurrency: "WTI",
    quoteCurrency: "USD",
    fmpSymbol: "WTIUSD",
    pipSize: 0.01,
    decimalPlaces: 2,
  },
  // Crypto
  {
    id: "BTC_USD",
    symbol: "BTC/USD",
    displayName: "Bitcoin",
    category: "crypto",
    baseCurrency: "BTC",
    quoteCurrency: "USD",
    fmpSymbol: "BTCUSD",
    coingeckoId: "bitcoin",
    pipSize: 0.01,
    decimalPlaces: 2,
  },
  {
    id: "ETH_USD",
    symbol: "ETH/USD",
    displayName: "Ethereum",
    category: "crypto",
    baseCurrency: "ETH",
    quoteCurrency: "USD",
    fmpSymbol: "ETHUSD",
    coingeckoId: "ethereum",
    pipSize: 0.01,
    decimalPlaces: 2,
  },
  // Indices
  {
    id: "US100",
    symbol: "US100",
    displayName: "Nasdaq 100",
    category: "index",
    baseCurrency: "NDX",
    fmpSymbol: "^IXIC",
    pipSize: 0.1,
    decimalPlaces: 1,
  },
  {
    id: "US30",
    symbol: "US30",
    displayName: "Dow Jones 30",
    category: "index",
    baseCurrency: "DJI",
    fmpSymbol: "^DJI",
    pipSize: 1,
    decimalPlaces: 0,
  },
];

export const TRADING_SESSIONS: Record<string, SessionInfo> = {
  sydney: {
    name: "Sydney",
    city: "Sydney",
    openHourUTC: 21,
    closeHourUTC: 6,
    timezone: "Australia/Sydney",
    color: "#8B5CF6",
  },
  tokyo: {
    name: "Tokyo",
    city: "Tokyo",
    openHourUTC: 0,
    closeHourUTC: 9,
    timezone: "Asia/Tokyo",
    color: "#F59E0B",
  },
  london: {
    name: "London",
    city: "London",
    openHourUTC: 7,
    closeHourUTC: 16,
    timezone: "Europe/London",
    color: "#3B82F6",
  },
  newyork: {
    name: "New York",
    city: "New York",
    openHourUTC: 12,
    closeHourUTC: 21,
    timezone: "America/New_York",
    color: "#EF4444",
  },
};

export const FRED_SERIES = {
  FED_FUNDS_RATE: "FEDFUNDS",
  TREASURY_2Y: "DGS2",
  TREASURY_10Y: "DGS10",
  TREASURY_30Y: "DGS30",
  DXY: "DTWEXBGS",
  CPI: "CPIAUCSL",
  GDP: "GDP",
  UNEMPLOYMENT: "UNRATE",
  FED_FUNDS_TARGET_UPPER: "DFEDTARU",
} as const;

export const REFRESH_INTERVALS = {
  PRICES: 30_000,
  NEWS: 300_000,
  ECONOMIC_CALENDAR: 900_000,
  FEAR_GREED: 300_000,
  BOND_YIELDS: 300_000,
  BIAS_RECALCULATION: 60_000,
  INDICATORS: 300_000, // 5 min — TradingView handles real-time charting
  LLM_ANALYSIS: 300_000,
  LLM_BATCH_ANALYSIS: 600_000,
  MARKET_SUMMARY: 600_000,
  ADR_DATA: 1_800_000, // 30 minutes — ADR changes slowly
} as const;

export const BIAS_THRESHOLDS = {
  STRONG_BEARISH: -45,
  BEARISH: -10,
  NEUTRAL_LOW: -10,
  NEUTRAL_HIGH: 10,
  BULLISH: 10,
  STRONG_BULLISH: 45,
} as const;

export const MAJOR_CURRENCIES = ["USD", "EUR", "GBP", "JPY", "AUD", "NZD", "CAD", "CHF"] as const;
