import type { Instrument, SessionInfo } from "@/lib/types/market";

export const INSTRUMENTS: Instrument[] = [
  // Forex
  {
    id: "EUR_USD",
    symbol: "EUR/USD",
    displayName: "Euro / US Dollar",
    category: "forex",
    alphavantageSymbol: "EUR",
    alphavantageToSymbol: "USD",
    finnhubSymbol: "OANDA:EUR_USD",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  {
    id: "GBP_USD",
    symbol: "GBP/USD",
    displayName: "British Pound / US Dollar",
    category: "forex",
    alphavantageSymbol: "GBP",
    alphavantageToSymbol: "USD",
    finnhubSymbol: "OANDA:GBP_USD",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  {
    id: "AUD_USD",
    symbol: "AUD/USD",
    displayName: "Australian Dollar / US Dollar",
    category: "forex",
    alphavantageSymbol: "AUD",
    alphavantageToSymbol: "USD",
    finnhubSymbol: "OANDA:AUD_USD",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  {
    id: "NZD_USD",
    symbol: "NZD/USD",
    displayName: "New Zealand Dollar / US Dollar",
    category: "forex",
    alphavantageSymbol: "NZD",
    alphavantageToSymbol: "USD",
    finnhubSymbol: "OANDA:NZD_USD",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  {
    id: "USD_JPY",
    symbol: "USD/JPY",
    displayName: "US Dollar / Japanese Yen",
    category: "forex",
    alphavantageSymbol: "USD",
    alphavantageToSymbol: "JPY",
    finnhubSymbol: "OANDA:USD_JPY",
    pipSize: 0.01,
    decimalPlaces: 3,
  },
  {
    id: "USD_CAD",
    symbol: "USD/CAD",
    displayName: "US Dollar / Canadian Dollar",
    category: "forex",
    alphavantageSymbol: "USD",
    alphavantageToSymbol: "CAD",
    finnhubSymbol: "OANDA:USD_CAD",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  {
    id: "USD_CHF",
    symbol: "USD/CHF",
    displayName: "US Dollar / Swiss Franc",
    category: "forex",
    alphavantageSymbol: "USD",
    alphavantageToSymbol: "CHF",
    finnhubSymbol: "OANDA:USD_CHF",
    pipSize: 0.0001,
    decimalPlaces: 5,
  },
  // Commodities
  {
    id: "XAU_USD",
    symbol: "XAU/USD",
    displayName: "Gold",
    category: "commodity",
    alphavantageSymbol: "XAU",
    alphavantageToSymbol: "USD",
    finnhubSymbol: "OANDA:XAU_USD",
    pipSize: 0.01,
    decimalPlaces: 2,
  },
  // Crypto
  {
    id: "BTC_USD",
    symbol: "BTC/USD",
    displayName: "Bitcoin",
    category: "crypto",
    alphavantageSymbol: "BTC",
    alphavantageToSymbol: "USD",
    coingeckoId: "bitcoin",
    pipSize: 0.01,
    decimalPlaces: 2,
  },
  {
    id: "ETH_USD",
    symbol: "ETH/USD",
    displayName: "Ethereum",
    category: "crypto",
    alphavantageSymbol: "ETH",
    alphavantageToSymbol: "USD",
    coingeckoId: "ethereum",
    pipSize: 0.01,
    decimalPlaces: 2,
  },
  // Indices
  {
    id: "US100",
    symbol: "US100",
    displayName: "Nasdaq 100",
    category: "index",
    alphavantageSymbol: "NDX",
    finnhubSymbol: "FOREXCOM:NSXUSD",
    pipSize: 0.1,
    decimalPlaces: 1,
  },
  {
    id: "US30",
    symbol: "US30",
    displayName: "Dow Jones 30",
    category: "index",
    alphavantageSymbol: "DJI",
    finnhubSymbol: "FOREXCOM:DJI",
    pipSize: 1,
    decimalPlaces: 0,
  },
  {
    id: "SPX500",
    symbol: "SPX500",
    displayName: "S&P 500",
    category: "index",
    alphavantageSymbol: "SPX",
    finnhubSymbol: "FOREXCOM:SPXUSD",
    pipSize: 0.1,
    decimalPlaces: 1,
  },
  {
    id: "US2000",
    symbol: "US2000",
    displayName: "Russell 2000",
    category: "index",
    alphavantageSymbol: "RUT",
    finnhubSymbol: "FOREXCOM:RUTUSD",
    pipSize: 0.1,
    decimalPlaces: 1,
  },
];

export const TRADING_SESSIONS: Record<string, SessionInfo> = {
  sydney: {
    name: "Sydney",
    city: "Sydney",
    openHourUTC: 21,
    closeHourUTC: 6,
    timezone: "Australia/Sydney",
    color: "#8B5CF6",
  },
  tokyo: {
    name: "Tokyo",
    city: "Tokyo",
    openHourUTC: 0,
    closeHourUTC: 9,
    timezone: "Asia/Tokyo",
    color: "#F59E0B",
  },
  london: {
    name: "London",
    city: "London",
    openHourUTC: 7,
    closeHourUTC: 16,
    timezone: "Europe/London",
    color: "#3B82F6",
  },
  newyork: {
    name: "New York",
    city: "New York",
    openHourUTC: 12,
    closeHourUTC: 21,
    timezone: "America/New_York",
    color: "#EF4444",
  },
};

export const FRED_SERIES = {
  FED_FUNDS_RATE: "FEDFUNDS",
  TREASURY_2Y: "DGS2",
  TREASURY_10Y: "DGS10",
  TREASURY_30Y: "DGS30",
  DXY: "DTWEXBGS",
  CPI: "CPIAUCSL",
  GDP: "GDP",
  UNEMPLOYMENT: "UNRATE",
  FED_FUNDS_TARGET_UPPER: "DFEDTARU",
} as const;

export const REFRESH_INTERVALS = {
  PRICES: 30_000,
  NEWS: 300_000,
  ECONOMIC_CALENDAR: 900_000,
  FEAR_GREED: 300_000,
  BOND_YIELDS: 300_000,
  BIAS_RECALCULATION: 60_000,
  INDICATORS: 60_000,
} as const;

export const BIAS_THRESHOLDS = {
  STRONG_BEARISH: -45,
  BEARISH: -10,
  NEUTRAL_LOW: -10,
  NEUTRAL_HIGH: 10,
  BULLISH: 10,
  STRONG_BULLISH: 45,
} as const;

export const MAJOR_CURRENCIES = ["USD", "EUR", "GBP", "JPY", "AUD", "NZD", "CAD", "CHF"] as const;
