"use client";

import { Cog, Sparkles } from "lucide-react";

export function AIvsRulesCallout() {
  return (
    <div className="panel rounded-lg overflow-hidden">
      <div className="grid grid-cols-1 lg:grid-cols-2 divide-y lg:divide-y-0 lg:divide-x divide-border/30">
        {/* Left: Mechanical */}
        <div className="p-5 border-l-[3px] border-l-[var(--bullish)]">
          <div className="flex items-center gap-2 mb-3">
            <div className="h-7 w-7 rounded-lg gradient-strip-green flex items-center justify-center text-white">
              <Cog className="h-3.5 w-3.5" />
            </div>
            <h3 className="text-sm font-semibold text-foreground">The Mechanical Brain</h3>
          </div>
          <div className="space-y-2 text-xs text-muted-foreground leading-relaxed">
            <p>
              Trade ideas are generated by <strong className="text-foreground">8 book-sourced mechanical systems</strong> that
              fire independently based on indicator values. There is no AI, no machine learning, no black box.
            </p>
            <p>
              Conviction scoring is pure math: signal agreement (how many systems align), regime match (do they
              fit the current market conditions), and impulse alignment (Elder&apos;s momentum filter).
            </p>
            <p>
              Position sizing, risk limits, and level snapping are all deterministic rules. Given the same
              market data, the system will always produce the same output.
            </p>
          </div>
          <div className="flex flex-wrap gap-1.5 mt-3">
            {["Deterministic", "Reproducible", "Book-sourced", "Rule-based"].map((tag) => (
              <span key={tag} className="text-[8px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded bg-bullish/10 text-bullish/70 border border-bullish/15">
                {tag}
              </span>
            ))}
          </div>
        </div>

        {/* Right: AI */}
        <div className="p-5 border-l-[3px] border-l-amber-500">
          <div className="flex items-center gap-2 mb-3">
            <div className="h-7 w-7 rounded-lg gradient-strip-amber flex items-center justify-center text-white">
              <Sparkles className="h-3.5 w-3.5" />
            </div>
            <h3 className="text-sm font-semibold text-foreground">Where AI Steps In</h3>
          </div>
          <div className="space-y-2 text-xs text-muted-foreground leading-relaxed">
            <p>
              AI is used in <strong className="text-foreground">3 places</strong>, all after the mechanical engine
              has already generated trade ideas:
            </p>
            <div className="space-y-1.5">
              {[
                { name: "Instrument Analysis", desc: "Narrates a single instrument's fundamentals + technicals into a readable report" },
                { name: "Batch Analysis", desc: "Generates market summaries for all 16 instruments simultaneously" },
                { name: "Desk Manager", desc: "Receives all A+/A mechanical setups and provides commentary, risk warnings, and a top pick" },
              ].map((ai, i) => (
                <div key={ai.name} className="flex gap-2 items-start">
                  <span className="text-[9px] font-mono text-amber-500/60 w-4 shrink-0 mt-0.5">{i + 1}.</span>
                  <div>
                    <span className="text-[10px] font-semibold text-amber-500/80">{ai.name}</span>
                    <span className="text-[10px] text-muted-foreground/50 ml-1">— {ai.desc}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="flex flex-wrap gap-1.5 mt-3">
            {["Narrator", "Interpreter", "Contextualizer"].map((tag) => (
              <span key={tag} className="text-[8px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded bg-amber-500/10 text-amber-500/70 border border-amber-500/15">
                {tag}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Bottom divider text */}
      <div className="px-5 py-3 bg-surface-2/30 border-t border-border/30 text-center">
        <p className="text-[11px] font-semibold text-muted-foreground">
          AI does <strong className="text-foreground">not</strong> generate trade ideas. It <strong className="text-foreground">explains</strong> them.
        </p>
      </div>
    </div>
  );
}
