"use client";

/**
 * DEPRECATED: Smart alerts are no longer a separate brain.
 * All alerts now fire from the mechanical signal engine inside AITradeDesk.
 * This file is kept for backward compatibility but is a no-op.
 */
export function useSmartAlerts() {
  // Alerts are now generated by useSetupAlerts (AITradeDesk) and
  // useTrackedSetups — both consume the mechanical signal engine.
  // Single brain, single pipeline.
}
