"use client";

import { motion } from "framer-motion";
import { Cog, Sparkles } from "lucide-react";

const mechanicalTags = ["Deterministic", "Reproducible", "Book-sourced", "Rule-based"];
const aiTags = ["Narrator", "Interpreter", "Contextualizer"];

const aiRoles = [
  { name: "Instrument Analysis", desc: "Narrates a single instrument's fundamentals + technicals into a readable report" },
  { name: "Batch Analysis", desc: "Generates market summaries for all 16 instruments simultaneously" },
  { name: "Desk Manager", desc: "Receives all A+/A mechanical setups and provides commentary, risk warnings, and a top pick" },
];

export function SystemMechanicalVsAi() {
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Mechanical */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="glass-card rounded-xl p-5 border-l-[3px] border-l-[var(--bullish)]"
        >
          <div className="flex items-center gap-2 mb-4">
            <div className="h-7 w-7 rounded-lg gradient-strip-green flex items-center justify-center text-white">
              <Cog className="h-3.5 w-3.5" />
            </div>
            <h4 className="text-sm font-semibold text-foreground">The Mechanical Brain</h4>
          </div>
          <div className="space-y-2 text-xs text-muted-foreground leading-relaxed">
            <p>
              Trade ideas are generated by <strong className="text-foreground">8 book-sourced mechanical systems</strong> that
              fire independently based on indicator values. Zero AI, zero machine learning, zero black box.
            </p>
            <p>
              Conviction scoring is pure math: <strong className="text-foreground">de-correlated cluster agreement</strong>,
              regime match, impulse alignment, market structure, and phase scoring.
            </p>
            <p>
              Position sizing, portfolio risk gates, and level snapping are all deterministic rules. Same data = same output.
            </p>
          </div>
          <div className="flex flex-wrap gap-1.5 mt-4">
            {mechanicalTags.map((tag, i) => (
              <motion.span
                key={tag}
                initial={{ opacity: 0, scale: 0.8 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="text-[8px] font-bold uppercase tracking-wider px-2 py-1 rounded-full bg-bullish/10 text-bullish/70 border border-bullish/15"
              >
                {tag}
              </motion.span>
            ))}
          </div>
        </motion.div>

        {/* AI */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="glass-card rounded-xl p-5 border-l-[3px] border-l-amber-500"
        >
          <div className="flex items-center gap-2 mb-4">
            <div className="h-7 w-7 rounded-lg gradient-strip-amber flex items-center justify-center text-white">
              <Sparkles className="h-3.5 w-3.5" />
            </div>
            <h4 className="text-sm font-semibold text-foreground">Where AI Steps In</h4>
          </div>
          <div className="space-y-3 text-xs text-muted-foreground leading-relaxed">
            <p>
              AI is used in <strong className="text-foreground">3 places</strong>, all after the mechanical engine
              has already generated trade ideas:
            </p>
            {aiRoles.map((ai, i) => (
              <div key={ai.name} className="flex gap-2 items-start">
                <span className="text-[9px] font-mono text-amber-500/60 w-4 shrink-0 mt-0.5">{i + 1}.</span>
                <div>
                  <span className="text-[10px] font-semibold text-amber-500/80">{ai.name}</span>
                  <span className="text-[10px] text-muted-foreground/50 ml-1">&mdash; {ai.desc}</span>
                </div>
              </div>
            ))}
          </div>
          <div className="flex flex-wrap gap-1.5 mt-4">
            {aiTags.map((tag, i) => (
              <motion.span
                key={tag}
                initial={{ opacity: 0, scale: 0.8 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="text-[8px] font-bold uppercase tracking-wider px-2 py-1 rounded-full bg-amber-500/10 text-amber-500/70 border border-amber-500/15"
              >
                {tag}
              </motion.span>
            ))}
          </div>
        </motion.div>
      </div>

      {/* Bottom callout */}
      <div className="glass-card rounded-xl px-5 py-3 text-center">
        <p className="text-[11px] font-semibold text-muted-foreground">
          AI does <strong className="text-foreground">not</strong> generate trade ideas. It <strong className="text-foreground">explains</strong> them.
        </p>
      </div>
    </div>
  );
}
